-- H2 & PostgreSQL compatible (IDENTITY is standard SQL:2003)
CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    age   INT          NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);
